Update neocomplcache to neocomplete, add FastFold to help with folds and improve the add/delete-submodule scripts

diff --git a/delete-submodule b/delete-submodule
--- a/delete-submodule
+++ b/delete-submodule
@@ -1,7 +1,25 @@
 #!/usr/bin/env bash
 
-[[ -z $1 ]] && exit 1
+[[ -z "$1" ]] && exit 1
 
-[[ -d "vim/bundle/${1}" ]] && git submodule deinit -f "vim/bundle/${1}" || echo "Couldn't run 'git submodule deinit vim/bundle/${1}', $1 does not exist"
-[[ -d "vim/bundle/${1}" ]] && git rm "vim/bundle/${1}" || echo "Couldn't run 'git rm vim/bundle/${1}', vim/bundle/${1} does not exist"
-[[ -d "${PWD}/.git/modules/vim/bundle/${1}" ]] && rm -rf "${PWD}/.git/modules/vim/bundle/${1}" || echo "Couldn't run 'rm -rf ${PWD}/.git/modules/vim/bundle/${1}', ${PWD}/.git/modules/vim/bundle/${1} does not exist"
+if [[ -d "vim/bundle/$1" ]]; then
+    git submodule deinit -f "vim/bundle/$1"
+else
+    printf '%s\n' "Couldn't run 'git submodule deinit vim/bundle/$1', does not exist" >&2
+    exit 1
+fi
+
+if [[ -d "vim/bundle/$1" ]]; then
+    git rm "vim/bundle/$1"
+else
+    printf '%s\n' "Couldn't run 'git rm vim/bundle/$1', does not exist" >&2
+    exit 1
+fi
+
+if [[ -d ".git/modules/vim/bundle/$1" ]]; then
+    rm -rf ".git/modules/vim/bundle/$1"
+else
+    printf '%s\n' "Couldn't run 'rm -rf .git/modules/vim/bundle/$1', does not exist" >&2
+    exit 1
+fi
+
