Tons of changes all in one commit because I'd broken a commit a while back and opted to simply reverse them all- Lots of colour changes, the update script now removes decommissioned bundles, gentags script can now have additional paths added to it when generating a tags file, README is much improved, fixed a few issues that required remapping some toggles, fixed a bunch of issues with the colourscheme between the terminal and gvim. You can now setup a custom config file to have loaded after the darkcloud-vimconfig ones, and there's a custom location for pathogen modules too, to make things tidier without necessarily needing to use an additional runtimepath. You can also create a file in your home directory to assign filetypes to programs, for use with the file manager. A file can be placed in ~/.vim/ with file associations and prorams to launch them with. The file manager will also open a file with vim by hitting shift+enter, since e isn't all that comfortablly placed. The vimrc can now also point to the darkcloud-vimconfig folder, rather than relying on the vim folder being in a specific location, and the after folder is now configured to work in the project too.

diff --git a/update b/update
--- a/update
+++ b/update
@@ -1,4 +1,17 @@
 #!/usr/bin/env bash
 
+cd "${0%/*}"
+
 git pull origin
 git submodule update --init --recursive
+
+
+[[ -f .gitmodules ]] && for each in vim/bundle/*; do
+    if [ -d "$each" ]; then
+        if [ -f "${each}/.git" ]; then
+            FILE=$(echo $each | grep -o -e "[^\/]*$")
+           [[ `cat .gitmodules | grep "path = " |  grep -o -e "[^\/]*$" | grep -c "${FILE}"` = 0 ]] && (rm -rf "${each}" && echo "Deleted: ${each}" || (echo -e "\033[01;31mWARNING\033[00m: '${each}' was removed upstream but couldn't be deleted here.\n\nPlease delete ${each} manually."; exit 1))
+        fi
+    fi
+done
+exit 0
